import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="bg-neutral-50 text-black dark:bg-neutral-900 dark:text-white">
				{children}
			</body>
		</html>
	)
}
